name: Deploy to S3

on: 
  push:
    branches:
      - 'master'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to S3
        run: aws s3 sync public/ s3://coolestguyinamerica.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
